# Generated by Django 5.1.6 on 2025-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='slug',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
