# Generated by Django 5.1.6 on 2025-02-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='slug',
        ),
    ]
