# Generated by Django 5.1.6 on 2025-02-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_postmodel_options_postmodel_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
