# Generated by Django 5.1.6 on 2025-02-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default=2, upload_to='posts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='short_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
