# Generated by Django 5.1.6 on 2025-02-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_verificationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationModel',
        ),
    ]
